browser=${browser}
timeout=${timeout}
selectors.version=${selectors.version}
locale=${locale}
display.stacktrace=${display.stacktrace}

jhipstersampleapp=${jhipstersampleapp}

# proxy configuration
http_proxy=${http_proxy}
https_proxy=${https_proxy}
no_proxy=${no_proxy}

jhipstersampleapp.app=${norarobot.app}

model.packages=com.yourcompany.norarobot.application.model

# type of input dataProvider (EXCEL, CSV, DB, REST, GHERKIN, noraui.data.xxx.YourCustomInputDataProvider)
dataProvider.in.type=EXCEL
# type of output dataProvider (EXCEL, CSV, REST, CONSOLE, noraui.data.xxx.YourCustomOutputDataProvider)
dataProvider.out.type=EXCEL

# authentication type (BASIC or empty)
authentication=

# type of dataProvider (ORACLE, MYSQL, POSTGRE)
dataProvider.db.type=
dataProvider.db.hostname=
dataProvider.db.port=
dataProvider.db.user=
dataProvider.db.password=
dataProvider.db.name=${database}

SpeedRegulator.annotation.enable=false
SpeedRegulators.annotation.enable=false
Time.annotation.enable=false
Times.annotation.enable=false
